### PR TITLE
mutable type in collection

### LINKED ISSUE #81: Mutable type in Collections
Giving two data class definitions:

```kotlin
data class Person(val name: String, val age: Int)

data class Group(val name: String, val members: List<Person>)
```

The helper class generated for `Group` comes

```kotlin
@`Group$DslMarker`
public class `Group$Mutable`(
  public var name: String,
  public var members: MutableList<Person>,
  public val old: Group,
)
```
In this case, if I want to make some change of person in `Group.members`, I should write

```kotlin
val nGroup = group.copy {
    val index = members.findTheOne()
    this.members[index] = this.members[index].copy {
      age++
    }
  }
```

Which is annoying.

It it possible to make the type of `Group$Mutable.members` to be `MutableList<Person$Mutable>`? Then I can simply use

```kotlin
val nGroup = group.copy {
    val index = members.findTheOne()
    this.members[index].age++
  }
```

### PR DESCRIPTION
**Pull request by xiaozhikang0916**
Fix #81 

Now items of list/set can be modified like issue #81 shows.

Map and generic type of non-primitive are currently not supported.

### CODE REVIEW

**Comment by serras** [comment]
@xiaozhikang0916 thanks for your contribution! This looks fantastic, let's check that CI is green and then I'll merge

**Comment by xiaozhikang0916** [comment]
The lint issue is fixed.

And, there will be some break change in this pr.

```kotlin
@Test
fun `edit list item in old school style`() {
  """
    data class Group(val p: List<Person>)
    data class Person(val age: Int)
    
    val g1 = Group(listOf(Person(1), Person(2)))
    val g2 = g1.copy { p[1] = p[1].copy(age = 3) }
    val age = g2.p[1].age
  """.trimIndent().evals("age" to 3)
}
```

This test will fail in this pr but pass in the main branch.

**Comment by serras** [comment]
> This test will fail in this pr but pass in the main branch.

why is it so? Is it because the copy method no longer exists or some other reason?

**Comment by xiaozhikang0916** [comment]
> > This test will fail in this pr but pass in the main branch.
> 
> why is it so? Is it because the copy method no longer exists or some other reason?

```kotlin
    data class Group(val p: List<Person>)
    data class Person(val age: Int)
```

In main branch, you will get a mutable class of `Group` like 

```kotlin
public class `Group$Mutable`(
  public var p: MutableList<Person>,
  public val old: Group,
)
```

Inside the `copy` scope, `p[1]` returns a instance of `Person` class, which is a kotlin data class so you can call the copy function.

------

In this pr, the mutable class of `Group` becomes

```kotlin
public class `Group$Mutable`(
  public var p: MutableList<`Person$Mutable`>,
  public val old: Group,
)
```

In the copy scope, `p[1]` will return the generated mutable class of `Person` rather than the original data class, which means, no copy function avaliable.

------

This is an intended change, but also break change. All data access operation of list/set inside a copy scope should have a check, and call of copy function should migrate to value-assign style.

**Pull request merged**
