### PR TITLE
Mutate utils part three

### PR DESCRIPTION
**Pull request by pablisco**
I forgot I had some bits half way on here for the documentation. However, we have the dokka now. Do we need this?

If not, I've renamed `mutateAllNotNullIndexed` to `mutateAllIndexedNotNull ` so we match stdlib's naming of [`mapIndexedNotNull`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/map-indexed-not-null.html)

### CODE REVIEW

**Comment by serras** [comment]
I would rather have the information in the Dokka (including the examples). The README is already quite long, and I think the usual function docs is much better for this section than a long list.

**Comment by serras** [comment]
@pablisco I'm happy to move the examples into the documentation comments, if you prefer working on something else

**Comment by pablisco** [comment]
> @pablisco I'm happy to move the examples into the documentation comments, if you prefer working on something else

If you could I would appreciate it 🙏 I'm deep into setting up tic tac toe 🤭

**Comment by serras** [comment]
> If you could I would appreciate it 🙏 I'm deep into setting up tic tac toe 🤭

Done! I've copied the examples to the docs, and added a "This is the mutable equivalent to X" to each function.

**Review by serras — APPROVED** [review]

**Pull request merged**
