### PR TITLE
[On Hold] Update kotlin to 1.7.20

### PR DESCRIPTION
**Pull request by pablisco**
Placeholder to upgrade to Kotlin `1.7.20`

Dokka `1.7.20` is not released yet. I'm not familiar with Dokka's release cycle though. Should we have a separate version for Dokka? Not a blocker for ksp, more for the mutate utils, really

### CODE REVIEW

**Comment by pablisco** [comment]
Hopefully, we'll have a release soon 🤞 
https://github.com/Kotlin/dokka/pull/2692

**Comment by serras** [comment]
[Dokka 1.7.20 released](https://github.com/Kotlin/dokka/releases/tag/v1.7.20), re-running checks

**Comment by serras** [comment]
Now waiting for a [new release of kotlin-compile-testing](https://github.com/tschuchortdev/kotlin-compile-testing/pull/320)

**Comment by serras** [comment]
Closed by #84

**Pull request closed without merging**
